{{- range $.Values.envs }}
{{- with . }}
{{ $configMapFullName := printf "apollo-configmap-%s" . -}}
{{ $configDBSuffix := printf "%s" . -}}
{{ $configServiceFullName := printf "apollo-config-service-%s" . -}}
{{ $adminServiceFullName := printf "apollo-admin-service-%s" . -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $adminServiceFullName }}
  labels:
    {{- include "apollo.service.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.adminService.replicaCount }}
  selector:
    matchLabels:
      app: {{ $adminServiceFullName }}
  {{- with $.Values.adminService.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $adminServiceFullName }}
    spec:
      {{- with $.Values.adminService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: volume-configmap-{{ $adminServiceFullName }}
          configMap:
            name: {{ $adminServiceFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
            defaultMode: 420
      initContainers:
      - name: test-mysql
        args:
        - mysql -h {{ $.Values.configdb.name }} -P {{ $.Values.configdb.port }} -D {{ $.Values.configdb.dbName }}{{ .}} -u {{ $.Values.configdb.userName }} -p{{ $.Values.configdb.password }} -e "show tables"
        command:
        - /bin/sh
        - -c
        image: {{ $.Values.configdb.imageName }}:{{ $.Values.configdb.imageTag }}
      containers:
        - name: {{ $.Values.adminService.name }}
          image: "{{ $.Values.adminService.image.repository }}:{{ $.Values.adminService.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.adminService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.adminService.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.adminService.config.profiles | quote }}
          {{- range $key, $value := $.Values.adminService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: volume-configmap-{{ $adminServiceFullName }}
              mountPath: /apollo-adminservice/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: {{ $.Values.adminService.port }}
            initialDelaySeconds: {{ $.Values.adminService.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.adminService.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.adminService.config.contextPath }}/health
              port: {{ $.Values.adminService.port }}
            initialDelaySeconds: {{ $.Values.adminService.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.adminService.readiness.periodSeconds }}
          resources:
            {{- toYaml $.Values.adminService.resources | nindent 12 }}
    {{- with $.Values.adminService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.adminService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.adminService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{ end }}