{{- range .Values.env }}
{{- with . }}
{{ $configMapFullName := printf "apollo-configmap-%s" . -}}
{{ $configDBSuffix := printf "apollo-config-db-%s" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $configMapFullName }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{include "apollo.configdb.servicePort" .}}/{{ .Values.configdb.dbName }}-$configDBSuffix{{ if .Values.configdb.connectionStringProperties }}?{{ .Values.configdb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.configdb.userName }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.configdb.password }}
    apollo.config-service.url = {{ include "apollo.configService.serviceUrl" .}}
    apollo.admin-service.url = {{ include "apollo.adminService.serviceUrl" .}}
    {{- if .Values.configService.config.contextPath }}
    server.servlet.context-path = {{ .Values.configService.config.contextPath }}
    {{- end }}
{{- end }}
{{ end }}
