{{- range .Values.envs }}
{{- with . }}
{{ $configDeploymentFullName := printf "apollo-config-deployment-%s" . -}}
{{ $configServiceFullName := printf "apollo-config-service-%s.%s.svc.cluster.local" $.Release.Namespace . -}}
{{ $configServiceDNSName := printf "apollo-config-service-%s" . -}}
{{ $adminServiceFullName := printf "apollo-admin-service-%s.%s.svc.cluster.local" $.Release.Namespace . -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $configServiceDNSName }}
  labels:
    {{- include "apollo.service.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ $.Values.configService.port }}
      targetPort: {{ $.Values.configService.port }}
  selector:
    app: {{ $configServiceFullName }}
{{- end }}
{{ end }}
