{{- range .Values.envs }}
{{- with . }}
{{ $configMapFullName := printf "apollo-configmap-%s" . -}}
{{ $configDBSuffix := printf "%s" . -}}
{{ $configServiceFullName := printf "apollo-config-service-%s" . -}}
{{ $adminServiceFullName := printf "apollo-admin-service-%s" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ $configDBSuffix }}-initdb-configmap
data:
  {{ set $ "__db" $configDBSuffix }}
  flyway.conf: {{ tpl ($.Files.Get "files/flyway/config/flyway.conf") $ | quote }}
  {{ range $path, $bytes := $.Files.Glob "files/flyway/config/sqls/*.*" }}
  {{ base $path }}: "{{ $.Files.Get $path | quote }}"
  {{ end }}
{{- end }}
{{ end }}