{{- range $.Values.envs }}
{{- with . }}
{{ $configDeploymentFullName := printf "apollo-config-deployment-%s" . -}}
{{ $configServiceFullName := printf "apollo-config-service-%s" . -}}
{{ $configMapFullName := printf "apollo-configmap-%s" . -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $configDeploymentFullName }}
  labels:
    {{- include "apollo.service.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.configService.replicaCount }}
  selector:
    matchLabels:
      app: {{ $configServiceFullName }}
  {{- with $.Values.configService.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $configServiceFullName }}
    spec:
      {{- with $.Values.configService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: volume-configmap-{{ $configMapFullName }}
          configMap:
            name: {{ $configMapFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
            defaultMode: 420
        - name: init-db
          configMap:
            name: config-{{ . }}-initdb-configmap
      initContainers:
      - name: test-mysql
        args:
        - mysql -h {{ $.Values.configdb.name }} -P {{ $.Values.configdb.port }} -D {{ $.Values.configdb.dbName }}{{ .}} -u {{ $.Values.configdb.userName }} -p{{ $.Values.configdb.password }} -e "show tables"
        command:
        - /bin/sh
        - -c
        image: {{ $.Values.configdb.imageName }}:{{ $.Values.configdb.imageTag }}
      - name: init-db
        image: flyway/flyway:7.0.2
        command: ["/bin/sh"]
        args: ["-c", "cd / && sh decode_sql.sh && flyway migrate"]
        # args: ["migrate"]
        env:
        - name: _CHECKSUM
          {{ $root := . }}
          {{ $checksum := "" }}
          {{ range $path, $bytes := $.Files.Glob "files/flyway/config/sqls/*.*" }}
          {{ $c := $.Files.Get $path | b64enc | sha256sum }}
          {{ $checksum = printf "%s-%s" $checksum $c | sha256sum }}
          {{ end }}
          value: "{{ printf "%s" $checksum }}"
        volumeMounts:
        - name: init-db
          mountPath: /flyway/sql_base64
        - name: init-db
          mountPath: /decode_sql.sh
          subPath: decode_sql.sh
        - name: init-db
          mountPath: /flyway/conf/flyway.conf
          subPath: flyway.conf
      containers:
        - name: {{ $configServiceFullName }}
          image: "{{ $.Values.configService.imageName }}:{{ $.Values.configService.imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.configService.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.configService.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.configService.config.profiles | quote }}
          {{- range $key, $value := $.Values.configService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: volume-configmap-{{ $configMapFullName }}
              mountPath: /apollo-configservice/config/application-github.properties
              subPath: application-github.properties
          readinessProbe:
            tcpSocket:
              port: {{ $.Values.configService.port }}
            initialDelaySeconds: {{ $.Values.configService.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.configService.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.configService.config.contextPath }}/health
              port: {{ $.Values.configService.port }}
            initialDelaySeconds: {{ $.Values.configService.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.configService.liveness.periodSeconds }}
          resources:
            {{- toYaml $.Values.configService.resources | nindent 12 }}
    {{- with $.Values.configService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.configService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.configService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{ end }}