apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.configdb.name }}-configmap
  labels:
    app: {{ .Values.configdb.name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
    create_db.sql: {{ tpl (.Files.Get "files/create_db.sql") . | quote }}
