kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.configdb.pvc }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi