kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.portalService.name }}-configmap
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{ $.Values.configdb.name }}:{{ $.Values.configdb.port }}/{{ .Values.portaldb.dbName }}{{ if .Values.portaldb.connectionStringProperties }}?{{ .Values.portaldb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.configdb.userName }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.configdb.password }}
    apollo.portal.envs = {{ join "," .Values.envs }}
    {{- if .Values.configService.contextPath }}
    server.servlet.context-path = {{ .Values.config.contextPath }}
    {{- end }}
  apollo-env.properties: |
    {{- range .Values.envs }}
    {{- with . }}
    {{ $env := printf "%s" . -}}
    {{ $configServiceFullName := printf "apollo-config-service-%s" . -}}
    {{ $env }}.meta = http://{{ printf "apollo-config-service-%s" . }}:{{ .Values.configService.service.port }}
    {{- end }}
    {{ end }}    
{{- range $fileName, $content := .Values.portalService.config.files }}
{{ $fileName | indent 2 }}: |
{{ $content | indent 4 }}
{{- end }}
