kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.portalService.name }}
  labels:
    {{- include "apollo.service.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.portalService.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $.Values.portalService.port }}
      targetPort: {{ $.Values.portalService.port }}
  selector:
    app: {{ .Values.portalService.name }}