kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.portalService.name }}
  labels:
    {{- include "apollo.portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.portalService.name }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.portalService.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configmap-{{ .Values.portalService.name }}
          configMap:
            name: {{ .Values.portalService.name }}
            items:
              - key: application-github.properties
                path: application-github.properties
              - key: apollo-env.properties
                path: apollo-env.properties
            {{- range $fileName, $content := .Values.portalService.config.files }}
              - key: {{ $fileName }}
                path: {{ $fileName }}
            {{- end }}
            defaultMode: 420
      containers:
        - name: {{ .Values.portalService.name }}
          image: "{{ .Values.portalService.image.repository }}:{{ .Values.portalService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.portalService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portalService.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.portalService.config.profiles | quote }}
          {{- range $key, $value := .Values.portalService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: configmap-{{ .Values.portalService.name }}
              mountPath: /apollo-portal/config/application-github.properties
              subPath: application-github.properties
            - name: configmap-{{ .Values.portalService.name }}
              mountPath: /apollo-portal/config/apollo-env.properties
              subPath: apollo-env.properties
          {{- range $fileName, $content := .Values.config.files }}
            - name: configmap-{{ .Values.portalService.name }}
              mountPath: /apollo-portal/config/{{ $fileName }}
              subPath: {{ $fileName }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.portalService.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.portalService.config.contextPath }}/health
              port: {{ .Values.portalService.containerPort }}
            initialDelaySeconds: {{ .Values.portalService.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.portalService.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}