kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.portalService.name }}
  labels:
    {{- include "apollo.portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.portalService.name }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.portalService.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.portalService.name }}-configmap
          configMap:
            name: {{ .Values.portalService.name }}-configmap
            items:
              - key: application-github.properties
                path: application-github.properties
              - key: apollo-env.properties
                path: apollo-env.properties
            {{- range $fileName, $content := .Values.portalService.config.files }}
              - key: {{ $fileName }}
                path: {{ $fileName }}
            {{- end }}
            defaultMode: 420
        - name: init-db
          configMap:
            name: portal-initdb-configmap
      initContainers:
      - name: init-db
        image: flyway/flyway:7.0.2
        command: ["/bin/sh"]
        args: ["-c", "cd / && sh decode_sql.sh && flyway migrate"]
        # args: ["migrate"]
        env:
        - name: _CHECKSUM
          {{ $root := . }}
          {{ $checksum := "" }}
          {{ range $path, $bytes := $.Files.Glob "files/flyway/portal/sqls/*.*" }}
          {{ $c := $.Files.Get $path | b64enc | sha256sum }}
          {{ $checksum = printf "%s-%s" $checksum $c | sha256sum }}
          {{ end }}
          value: "{{ printf "%s" $checksum }}"
        volumeMounts:
        - name: init-db
          mountPath: /flyway/sql_base64
        - name: init-db
          mountPath: /decode_sql.sh
          subPath: decode_sql.sh
        - name: init-db
          mountPath: /flyway/conf/flyway.conf
          subPath: flyway.conf
      containers:
        - name: {{ .Values.portalService.name }}
          image: "{{ .Values.portalService.image.repository }}:{{ .Values.portalService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.portalService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portalService.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.portalService.config.profiles | quote }}
          {{- range $key, $value := .Values.portalService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.portalService.name }}-configmap
              mountPath: /apollo-portal/config/application-github.properties
              subPath: application-github.properties
            - name: {{ .Values.portalService.name }}-configmap
              mountPath: /apollo-portal/config/apollo-env.properties
              subPath: apollo-env.properties
          {{- range $fileName, $content := .Values.portalService.config.files }}
            - name: {{ .Values.portalService.name }}-configmap
              mountPath: /apollo-portal/config/{{ $fileName }}
              subPath: {{ $fileName }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.portalService.containerPort }}
            initialDelaySeconds: {{ .Values.portalService.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.portalService.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.portalService.config.contextPath }}/health
              port: {{ .Values.portalService.containerPort }}
            initialDelaySeconds: {{ .Values.portalService.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.portalService.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.portalService.resources | nindent 12 }}
    {{- with .Values.portalService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portalService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portalService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}